### ISSUE TITLE
HTTP不能被上游

### ISSUE THREAD

**Issue by Khaos116** [jayluxferro/ProxyMe#1]
配合Charles抓包时，Https是可以使用的，但是http的连接不会被转发

**Comment by jayluxferro** [comment]
Hi @Khaos116 , you have to make sure you install the Charles Proxy certificate as part of the system root certificate.

On Android 5 and above, user installed certificates are not accepted as system certificate. I use the script below to upload **`burpsuite`** certificate on the android device. It requires root access though. You can replace **`burp.der`** with any other certificate.

```
openssl x509 -inform DER -in burp.der -out cacert.pem
res=$(openssl x509 -inform PEM -subject_hash_old -in cacert.pem |head -1)
mv cacert.pem $res.0
adb root
adb remount
adb push $res.0 /system/etc/security/cacerts
adb shell chmod 644 /system/etc/security/cacerts/$res.0
rm $res.0
adb reboot
```
