### ISSUE TITLE
Update to list user apps as well

### ISSUE THREAD

**Issue by jivanirutvik** [jayluxferro/ProxyMe#2]
For now only system app is showing in allowed/disallowed application list. Update it to list user apps as well
Thanks.

**Comment by jayluxferro** [comment]
@jivanirutvik , it shows both system and user apps. You can show a screenshot of what exactly the issue is and provide extra details on what device you're running it on, android version, etc.

**Comment by jivanirutvik** [comment]
> @jivanirutvik , it shows both system and user apps. You can show a screenshot of what exactly the issue is and provide extra details on what device you're running it on, android version, etc.

I am currently on Android 13 ( OnePlus Nord 2 ).  [Watch this video](https://otpworld.in/Record_2023-04-30-20-35-34.mp4).

**Comment by jayluxferro** [comment]
@jivanirutvik , I updated the app here: https://github.com/jayluxferro/ProxyMe/releases/download/v1.0.0/ProxyMe_v1.0.0.apk

Try and let me know if it works fine.

Thanks

**Comment by jivanirutvik** [comment]
Yeah, that's working. Thanks

**Comment by jivanirutvik** [comment]
> @jivanirutvik , I updated the app here: https://github.com/jayluxferro/ProxyMe/releases/download/v1.0.0/ProxyMe_v1.0.0.apk
> 
> Try and let me know if it works fine.
> 
> Thanks

Yeah, that's working. Thanks
